# Generated by Django 5.0.1 on 2024-02-21 23:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luigi_pizza', '0002_cheese_crust_sauce_size_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('expiry_date', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
