# Generated by Django 5.0.1 on 2024-02-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luigi_pizza', '0009_alter_order_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Luigi_pizza.pizza'),
        ),
    ]
